apiVersion: v1
kind: PersistentVolume
metadata:
  name: cronjob-timestamp-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/cronjob-timestamp
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cronjob-timestamp-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-timestamp
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            command:
            - /bin/sh
            - -c
            - date >> /timestampdata/timestamp.log
            volumeMounts:
            - name: timestamp-storage
              mountPath: /timestampdata
          restartPolicy: OnFailure
          volumes:
          - name: timestamp-storage
            persistentVolumeClaim:
              claimName: cronjob-timestamp-pvc
              readOnly: false

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app.kubernetes.io/name: myatest-podpp
spec:
  containers:
  - name: test-pod
    image: nginx
    volumeMounts:
      - name: timestamp-storage
        mountPath: /timestampdata
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.5"
      requests:
        memory: "100Mi"
        cpu: "0.2"
  volumes:
  - name: timestamp-storage
    persistentVolumeClaim:
      claimName: cronjob-timestamp-pvc
      readOnly: false
