apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-cidr-range
  namespace: default
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      name: random-pod
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/24
