# Create a CronJob named `daily-report` that runs every day at 1 AM using `busybox`.

apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-report
  namespace: default
spec:
  schedule: "* 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: create-report
            image: busybox:1.28
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
