apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-db-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/mysql-db
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_USER: d2ViLXVzZXI=
  MYSQL_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db-deployment
spec:
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: mysql-db-secrets
        resources:
          requests:
            memory: "300Mi"
            cpu: "0.8"
          limits:
            memory: "500Mi"
            cpu: "1500m"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-db-vol
          mountPath: /data
      volumes:
      - name: mysql-db-vol
        persistentVolumeClaim:
          claimName: mysql-db-pvc
          readOnly: false



  
